extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
globals:
  insights: writable
rules:
  no-unused-vars:
    - warn
    - ignoreRestSiblings: true
  prettier/prettier:
    - error
    - singleQuote: true
  sort-imports:
    - error
    - ignoreDeclarationSort: true
