# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: user-preferences-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: user-preferences
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      title: User Preferences
      deploymentRepo: https://github.com/RedHatInsights/user-preferences-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/user-preferences
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/user-preferences/fed-mods.json"
        defaultDocumentTitle: User Preferences | User Preferences
        modules:
        - id: user-preferences-notifications
          module: "./RootApp"
          routes:
          - pathname: "/user-preferences"
          - pathname: "/user-preferences/email"
          - pathname: "/settings/notifications/user-preferences"
      bundleSegments:
        - segmentId: email-preferences
          bundleId: user-preferences
          navItems:
            - title: Email preferences
              id: emailPreferences
              href: "/user-preferences/email"
          position: 300
      
      searchEntries:
        - id: user-preferences
          title: Email preferences
          href: /user-preferences/email
          description: Configure your email preferences and their schedule
          alt_title:
            - email schedule
            - errata

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/user-preferences-frontend